### ISSUE TITLE
Could you provide the VG-SGG-dicts-with-attri.json

### ISSUE THREAD

**Issue by weiyunfei** [KaihuaTang/Scene-Graph-Benchmark.pytorch#1]
Hi, Kaihua,
Thanks for your excellent framework. I encountered trouble when I tried to run your code. 
It needs the _VG-SGG-dicts-with-attri.json_ file to make the code run, but I find that you have only provided the link of  _VG-SGG-with-attri.h5_ in the [prepare and dataset.md](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/DATASET.md). Could you please tell me the way to get the _VG-SGG-dicts-with-attri.json_?
Your reply will be appreciated.

Good day!

**Comment by KaihuaTang** [comment]
since VG-SGG-dicts-with-attri.json is only 19kb, I directly uploaded it to the directory: https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/tree/master/datasets/vg

**Comment by weiyunfei** [comment]
Thanks for your kind help.
