### ISSUE TITLE
frozen backbone detector

### ISSUE THREAD

**Issue by ranran9991** [KaihuaTang/Scene-Graph-Benchmark.pytorch#105]
## ❓ Questions and Help
Can you point me to the line in which the backbone detector is being freezed?

**Comment by ranran9991** [comment]
Found it 

https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/3f8074e9e8d483a5c746df70b0bbfecec19f2632/tools/relation_train_net.py#L52

**Comment by bibekyess** [comment]
Hi @ranran9991, I didn't understand why we freeze the backbone detector in relationship prediction as we are training from scratch? Can you please explain why we are doing so? 
Thank you for your help!

**Comment by ranran9991** [comment]
> Hi @ranran9991, I didn't understand why we freeze the backbone detector in relationship prediction as we are training from scratch? Can you please explain why are we doing so? Thank you for your help!

I'm not the author of the paper, you should be asking @KaihuaTang that as he is the original writer of the paper and the maintainer of this package.

**Comment by bibekyess** [comment]
@ranran9991 I of course know who is the author. I just asked in this issue as you were searching for the point of frozen detector and I thought you might have some insight on why is it being done. Anyways, Thanks for a quick response and have a good day!! :)
