### ISSUE TITLE
Attributes for custom prediction

### ISSUE THREAD

**Issue by vrdn-23** [KaihuaTang/Scene-Graph-Benchmark.pytorch#106]
## ❓ Questions and Help
Is it possible to generate attribute prediction for custom images? I've pretrained the detector and scene graph generation model with ATTRIBUTE_ON: True but when running inference on custom images, it seems as if it is not predicting the attributes for the objects. 

Is there something else I need to take care of?

**Comment by vrdn-23** [comment]
Solved this by making edits to maskrcnn_benchmark/engine/inference.py

**Comment by dyang-TUM** [comment]
Can you please share how to edit in the inference.py? Thanks a lot for your help. @vrdn-23
