### ISSUE TITLE
Dataloader bug

### ISSUE THREAD

**Issue by xuewyang** [KaihuaTang/Scene-Graph-Benchmark.pytorch#109]
## 🐛 Bug

Hi Kaihua,
Thank you for your wonderful work. 

Is [here](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d0ffa40d92133d7d865e531146de82c8c8a344c0/maskrcnn_benchmark/data/datasets/visual_genome.py#L364) a bug? Should it be like all_boxes[:, 2:] = all_boxes[:, :2] + all_boxes[:, 2:] / 2? cx, cy are the center coordinates, right? Thank you.

**Comment by waxnkw** [comment]
> ## bug Bug
> 
> Hi Kaihua,
> Thank you for your wonderful work.
> 
> Is [here](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d0ffa40d92133d7d865e531146de82c8c8a344c0/maskrcnn_benchmark/data/datasets/visual_genome.py#L364) a bug? Should it be like all_boxes[:, 2:] = all_boxes[:, :2] + all_boxes[:, 2:] / 2? cx, cy are the center coordinates, right? Thank you.

it seems that all_boxes[:, :2] has already been modifed from cx, cy to x1, x2 in the [previous line](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d0ffa40d92133d7d865e531146de82c8c8a344c0/maskrcnn_benchmark/data/datasets/visual_genome.py#L363) of the line you quoted.

**Comment by xuewyang** [comment]
> > ## bug Bug
> > Hi Kaihua,
> > Thank you for your wonderful work.
> > Is [here](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d0ffa40d92133d7d865e531146de82c8c8a344c0/maskrcnn_benchmark/data/datasets/visual_genome.py#L364) a bug? Should it be like all_boxes[:, 2:] = all_boxes[:, :2] + all_boxes[:, 2:] / 2? cx, cy are the center coordinates, right? Thank you.
> 
> it seems that all_boxes[:, :2] has already been modifed from cx, cy to x1, x2 in the [previous line](https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d0ffa40d92133d7d865e531146de82c8c8a344c0/maskrcnn_benchmark/data/datasets/visual_genome.py#L363) of the line you quoted.

Yes, that is right. Thank you.
