### ISSUE TITLE
About VG-SGG-with-attri.h5 

### ISSUE THREAD

**Issue by Zhang-GK** [KaihuaTang/Scene-Graph-Benchmark.pytorch#112]
## ❓ Questions and Help
OSError: Unable to open file (unable to open file: name = 'datasets/vg/VG-SGG-with-attri.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
When I try to run this model with my own data, which is only including images. I have met this error. Could you please help me solve it? Thanks in advance!

**Comment by zhangj1an** [comment]
Hi, I met exact the error as this. Did you solve this issue? Any help is appreciated. Thanks!

**Comment by zhangj1an** [comment]
For anyone met the same problem, the link for the needed file is https://github.com/danfeiX/scene-graph-TF-release/blob/master/data_tools/README.md

**Comment by MeinhardMark** [comment]
I have another problem with this file:
`OSError: Unable to open file (truncated file: eof = 146680184, sblock->base_addr = 0, stored_eof = 150724042)`

**Comment by stannum2** [comment]
> I have another problem with this file:我这个文件还有另一个问题： `OSError: Unable to open file (truncated file: eof = 146680184, sblock->base_addr = 0, stored_eof = 150724042)`

same problem do you have any solution？
