### ISSUE TITLE
head_rect, tail_rect

### ISSUE THREAD

**Issue by alibabadoufu** [KaihuaTang/Scene-Graph-Benchmark.pytorch#13]
## ❓ Questions and Help
Thanks for your contribution. I really appreciate your efforts for this repo.

May I ask what is the usage for this head_rect and tail rect in roi_relation_feature_extractors.py? I couldn't get it even though I have read through the papers (VCTree, Motitf..).

**Comment by KaihuaTang** [comment]
> head_rect

This part of the code is created by neural-motifs. It generates two 0/1 masks to represent the locations and shapes of subject&object bounding boxes, then sends them to a conv layer for spatial features of subs/objs.

**Comment by alibabadoufu** [comment]
why is resolution * 4 - 1?
-1 means that it excludes the relation between two identical objects, but it needs to multiply by 4? Thanks so much for your answer in advanced.

**Comment by KaihuaTang** [comment]
> 1 means that it excludes the relation between two identical objects, but it needs to multiply by 4? Thanks so much for your answer in advanced.

I think you misunderstand my previous answer. They are two masks generated to mark the location of sub and obj on the original image. The size of the masks should be the same as the original image, so they times 4 to reverse the downsamplings of previous max-poolings and minus 1 in case the floor operation was involved in the downsamplings.

**Comment by alibabadoufu** [comment]
> > 1 means that it excludes the relation between two identical objects, but it needs to multiply by 4? Thanks so much for your answer in advanced.
> 
> I think you misunderstand my previous answer. They are two masks generated to mark the location of sub and obj on the original image. The size of the masks should be the same as the original image, so they times 4 to reverse the downsamplings of previous max-poolings and minus 1 in case the floor operation was involved in the downsamplings.

Thanks so much!
