### ISSUE TITLE
Groundtruth of VisualGenome Dataset 

### ISSUE THREAD

**Issue by Kenneth-Wong** [KaihuaTang/Scene-Graph-Benchmark.pytorch#14]
## ❓ Questions and Help
In line 147 in the visual_genome.py (function get_groundtruth), what is the purpose to add "if (random.random() > 0.5):"?

**Comment by KaihuaTang** [comment]
> ## ❓ Questions and Help
> In line 147 in the visual_genome.py (function get_groundtruth), what is the purpose to add "if (random.random() > 0.5):"?

Sometimes two objects may have multiple different ground-truth predicates in VisualGenome. In this case, when we construct GT annotations, random selection allows later predicates having the chance to overwrite the precious collided predicate.

**Comment by Kenneth-Wong** [comment]
Thanks your reply.
