### ISSUE TITLE
CausalAnalysisPredictor-Motif无法复现结果

### ISSUE THREAD

**Issue by Nora-Zhang98** [KaihuaTang/Scene-Graph-Benchmark.pytorch#144]
## ❓ Questions and Help
作者您好，我在复现您的代码时遇到了一些问题。我的实验结果是这样的，TDE和none都无法达到预期结果。我训练了4w次，训练时EFFECT_TYPE为none，测试时EFFECT_TYPE设为TDE，CONTEXT_LAYER选择了motif，FUSION_TYPE选择sum。我考虑过是否为过拟合的问题，但我用训练了2.8w的模型去测试时，结果比图示更糟。想请教您一下为何会发生这种情况，万分感谢!
![2021-10-30 11-45-23 的屏幕截图](https://user-images.githubusercontent.com/60804365/139519237-05774ce6-419b-439c-95d6-b43f022b5531.png)

**Comment by Nora-Zhang98** [comment]
问题已解决
问题原因：我只使用了一张卡进行训练，原始bz=2，lr=lr * rl_factor，在修改bz=8，lr=lr后问题得以解决
![2021-11-02 11-30-52 的屏幕截图](https://user-images.githubusercontent.com/60804365/139782708-feb4e988-58c2-4461-a5f7-cf877596b547.png)

**Comment by zhanwenchen** [comment]
Thank you for pointing out that lr_factor=batch_size needs to be removed.
