### ISSUE TITLE
parameter passing

### ISSUE THREAD

**Issue by alibabadoufu** [KaihuaTang/Scene-Graph-Benchmark.pytorch#15]
## ❓ Questions and Help

https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/697488f4d95dbdc1bc71b080318739825d7de8c2/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py#L265

In this line you are passing [roi_features, proposals, logger] to the LSTMcontext class

https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/697488f4d95dbdc1bc71b080318739825d7de8c2/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_motifs.py#L355

But shouldn't you pass these parameter [x, proposals, rel_pair_idxs] instead? What I understand is the [rel_pair_idxs] is referred to [logger] based on your current code implementation.

**Comment by KaihuaTang** [comment]
You are right. I made a mistake here. However, neither rel_pair_idxs nor logger is used in the model_motifs.py, so it won't cause any serious problems. 

In those models do matter, like

https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/697488f4d95dbdc1bc71b080318739825d7de8c2/maskrcnn_benchmark/modeling/roi_heads/relation_head/roi_relation_predictors.py#L376

I used the correct inputs.
