### ISSUE TITLE
detail about GLOVE_DIR /home/kaihua/glove?

### ISSUE THREAD

**Issue by Thinking-more** [KaihuaTang/Scene-Graph-Benchmark.pytorch#167]
## ❓ Questions and Help
作者您好，我想知道这个glove是glove.6B的还是其它版本的呀，使用的维数是多少呢？希望您在有空时可以解答下我的疑惑，非常感谢!

**Comment by cpperrpr** [comment]
Have you solved it? I also have doubts about this

**Comment by Thinking-more** [comment]
> Have you solved it? I also have doubts about this

glove.6B.200d
