### ISSUE TITLE
INFO File not found:  /home/user/glove/glove.6B.200d.pt

### ISSUE THREAD

**Issue by Ceazy-Gentleman** [KaihuaTang/Scene-Graph-Benchmark.pytorch#178]
## ❓ Questions and Help
INFO File not found:  /home/user/glove/glove.6B.200d.pt，
I do not known how to download the file. Can you tell me where I can download it! please!

**Comment by KaihuaTang** [comment]
The link is http://nlp.stanford.edu/data/glove.6B.zip
As far as I remember, the project will automatically detect and download the glove.6B.200d.pt.
Please check line 179 in https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d7111b27c26db89f0127b171f76c695806cb4a3a/maskrcnn_benchmark/modeling/roi_heads/relation_head/utils_motifs.py#L151

**Comment by Ceazy-Gentleman** [comment]
Thank you very much! @KaihuaTang  

According to your prompt, I solved the problem after deleting the command 'GLOVE_DIR /home/user/glove'. it will automatically create the fold and download the required files at the first time! 

> The link is http://nlp.stanford.edu/data/glove.6B.zip As far as I remember, the project will automatically detect and download the glove.6B.200d.pt. Please check line 179 in
> 
> https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d7111b27c26db89f0127b171f76c695806cb4a3a/maskrcnn_benchmark/modeling/roi_heads/relation_head/utils_motifs.py#L151
d files at the first time! @ 

> The link is http://nlp.stanford.edu/data/glove.6B.zip As far as I remember, the project will automatically detect and download the glove.6B.200d.pt. Please check line 179 in
> 
> https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/d7111b27c26db89f0127b171f76c695806cb4a3a/maskrcnn_benchmark/modeling/roi_heads/relation_head/utils_motifs.py#L151
