### ISSUE TITLE
GPU memory 

### ISSUE THREAD

**Issue by Kenneth-Wong** [KaihuaTang/Scene-Graph-Benchmark.pytorch#18]
## ❓ Questions and Help

I found that the object detector is trained with the ResNeXt101-32x8d-FPN backbone. I want to know the memory it used on a single GPU. I have tried the ResNeXt101-64x4d-FPN backbone and the peak memory it used is about 11GB on a single GPU (2 images per GPU, and memory of each of my GPU is 12GB). I wonder if it's enough for further SGG training because additional modules will be added. Should I reduce the number of images on a single GPU to one?

**Comment by KaihuaTang** [comment]
Don't worry. In SGG training, the ResNeXt101-32x8d-FPN backbone is frozen,  so the memory usage won't be exorbitant. My batch size is 8-12 for two 2080ti (11GB each).

**Comment by Kenneth-Wong** [comment]
Thanks.
