### ISSUE TITLE
Fine-tuning on the pre-trained motif-sgdet

### ISSUE THREAD

**Issue by bibekyess** [KaihuaTang/Scene-Graph-Benchmark.pytorch#180]
## ❓ Questions and Help
Hello, Thanks for this awesome work! I want to fine-tune this pre-trained motif-sgdet model on another custom dataset. I also made the dataset of 1000 images following the guidelines as mentioned on previous issues. But, I didn't get an idea of how to fine-tune this on top of the already trained model?
Can anyone who has already done this help me or give me some hint?

Thank you!

**Comment by bibekyess** [comment]
I think I solved it. 
For others with similar doubt, I randomly initialized the weight parameters for the following layers and used the same weight parameters for the other layers in the MotifPredictor:
'module.roi_heads.box.predictor.cls_score.weight', 'module.roi_heads.box.predictor.cls_score.bias', 'module.roi_heads.box.predictor.bbox_pred.weight', 'module.roi_heads.box.predictor.bbox_pred.bias', 'module.roi_heads.relation.predictor.context_layer.obj_embed1.weight', 'module.roi_heads.relation.predictor.context_layer.obj_embed2.weight', 'module.roi_heads.relation.predictor.context_layer.decoder_rnn.obj_embed.weight', 'module.roi_heads.relation.predictor.context_layer.decoder_rnn.out_obj.weight', 'module.roi_heads.relation.predictor.context_layer.decoder_rnn.out_obj.bias', 'module.roi_heads.relation.predictor.rel_compress.weight'], 'module.roi_heads.relation.predictor.rel_compress.bias', 'module.roi_heads.relation.predictor.freq_bias.obj_baseline.weight'.

**Comment by narchitect** [comment]
@bibekyess Hi, Thanks for sharing your solution. I try your way to fine tune their checkpoint of SDGet model, but I can't find your weights in the log file. May I ask you let me know your way in more steps? like how to find the weights you mentioned above, and how to initialize the weight parameters for fine-turning with a custom dataset. because I'm a beginner to use a SGG ML model..
