### ISSUE TITLE
AssertionError assert rois.size(0) > 0

### ISSUE THREAD

**Issue by yangzhaopeng3** [KaihuaTang/Scene-Graph-Benchmark.pytorch#185]
## ❓ Questions and Help
![image](https://user-images.githubusercontent.com/44217469/194054718-e71207d9-98a4-4e66-9067-a016ce1276d9.png)

Hi Kaihua, thanks for your great work.
When I am using this codebase with `batch_size=1`  and `SGCLS` setting, the following `assertion error` would occur occasionally. 
I have checked the dataset while it seems that all image would have at least 1 bounding box, so I couldn't figure out the problem. Any idea? Thanks.

**Comment by missyoudaisy** [comment]
How did you solve the problem? I also met this occasionally.

**Comment by MengHsir** [comment]
Possible reasons:
- The `datasets` method applies `box_clip` (clipping boxes to image boundaries) and `filter_instances` (removing invalid boxes) to bounding boxes.
- After these operations, some images end up with only 0 or 1 valid bounding box.
- The relation detection module requires at least two objects to form relation pairs, which triggers an assertion error.
