### ISSUE TITLE
SGDet on Custom Images

### ISSUE THREAD

**Issue by yayalvhai** [KaihuaTang/Scene-Graph-Benchmark.pytorch#190]
## ❓ Questions and Help
If I just detect scene graphs on one image, do I need to download the VG dataset?

**Comment by yayalvhai** [comment]
2023-02-09 21:19:54,192 maskrcnn_benchmark.data.build INFO: get dataset statistics...
2023-02-09 21:19:54,193 maskrcnn_benchmark.data.build INFO: Unable to load data statistics from: /home/user/projects/Scene-Graph-Benchmark/checkpoints/causal-motifs-sgdet/VG_stanford_filtered_with_attribute_train_statistics.cache

so the solution is to download the VG dataset ( 9GB+5GB) ?

**Comment by ubuntufan4life** [comment]
@yayalvhai 
Could you tell me how you solved the problem? Did you really have to download the VG dataset in the end?

**Comment by yayalvhai** [comment]
> @yayalvhai
> Could you tell me how you solved the problem? Did you really have to download the VG dataset in the end 

yeah. If just SGDet, you do not need to download VG datasets

**Comment by zl535320706** [comment]
> 2023-02-09 21:19:54,192 maskrcnn_benchmark.data.build INFO: get dataset statistics... 2023-02-09 21:19:54,193 maskrcnn_benchmark.data.build INFO: Unable to load data statistics from: /home/user/projects/Scene-Graph-Benchmark/checkpoints/causal-motifs-sgdet/VG_stanford_filtered_with_attribute_train_statistics.cache
> 
> so the solution is to download the VG dataset ( 9GB+5GB) ?

After download Visual Genome image (108249 items), put it into datasets/vg/VG_100K and run  bash scripts/test.sh, the program automatically generate VG_stanford_filtered_with_attribute_train_statistics.cache in checkpoints/PE-NET_PredCls/

@ubuntufan4life

**Comment by majianbo3** [comment]
> > 2023-02-09 21：19：54，192 maskrcnn_benchmark.data.build INFO：获取数据集统计信息. 2023-02-09 21：19：54，193 maskrcnn_benchmark.data.build信息：无法从以下位置加载数据统计信息：/home/user/projects/Scene-Graph-Benchmark/checkpoints/case-motifs-sgdet/VG_斯坦福大学_filtered_with_attribute_train_statistics.cache
> > 所以解决方案是下载VG数据集（9 GB +5GB）？
> 
> 下载Visual Genome图像（108249个项目）后，将其放入datasets/vg/VG_100K并运行bash脚本/test.sh，程序自动生成VG_斯坦福大学_filtered_with_attribute_train_statistics.cache in checkpoints/PE-NET_PredCls/
> 
> @ubuntufan4life

sorry,i dont know where /test.sh

**Comment by zuiyeye** [comment]
``> > @yayalvhai
> > 你能告诉我你是如何解决这个问题的吗？你最后真的必须下载 VG 数据集吗？
> 
> 是的。如果只是 SGDet，则无需下载 VG 数据集

我在进行readme文件中SGDet on Custom Images这一步，如果不需要下载数据集，为何我还是有
2024-11-06 14:20:19,037 maskrcnn_benchmark.data.build INFO: Unable to load data statistics from: /home/njcam/cy/checkpoints/causal-motifs-sgdet/VG_stanford_filtered_with_attribute_train_statistics.cache
顺带一提，这个路径指向的是作者提供的预训练模型权重解压后文件夹里的相应文件
![捕获](https://github.com/user-attachments/assets/3320f1fa-dea4-44c3-a3a2-4c5d5cde24c4)

   以防是我的命令出现问题，以下是我使用的命令：
`CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 10027 --nproc_per_node=1 tools/relation_test_net_cy.py --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX False MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE TDE MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs TEST.IMS_PER_BATCH 1 DTYPE "float16" GLOVE_DIR /home/njcam/cy/glove MODEL.PRETRAINED_DETECTOR_CKPT /home/njcam/cy/checkpoints/causal-motifs-sgdet OUTPUT_DIR /home/njcam/cy/checkpoints/causal-motifs-sgdet TEST.CUSTUM_EVAL True TEST.CUSTUM_PATH /home/njcam/cy/coco/Scene-Graph-Benchmark.pytorch/datasets/test.jpg DETECTED_SGG_DIR /home/njcam/cy/checkpoints/output_pat`

**Comment by zuiyeye** [comment]
> ``> >@yayalvhai
> 
> > > 你能告诉我你是如何解决这个问题的吗？你最后真的必须下载 VG 数据集吗？
> > 
> > 
> > 是的。如果只是SGDet，则消耗下载VG数据集
> 
> 我在进行readme文件中SGDet on Custom Images这一步，如果不需要下载数据集，为何我还是有 2024-11-06 14:20:19,037 maskrcnn_benchmark.data.build INFO: Unable to load data stats from: /home /njcam/cy/checkpoints/causal-motifs-sgdet/VG_stanford_filtered_with_attribute_train_statistics.cache 顺带一提，这个路径指向的是作者提供的预训练模型权重解压后文件夹里的相应文件 ![捕获](https://private-user-images.githubusercontent.com/150881585/383432278-3320f1fa-dea4-44c3-a3a2-4c5d5cde24c4.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzU4NzMsIm5iZiI6MTczMDg3NTU3MywicGF0aCI6Ii8xNTA4ODE1ODUvMzgzNDMyMjc4LTMzMjBmMWZhLWRlYTQtNDRjMy1hM2EyLTRjNWQ1Y2RlMjRjNC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQwNjQ2MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2I0MjU3YmQ5NDhhNzFjMzdmMzlhNDYwYmRiNjdhYWE0YzE2MTU1YTBmYWFlOTU5NzdjMzQ4M2Q5NTYzMmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fmkUYAcxVfIF3qO3fzmoxMgcRobAJE-1L0fss69287s)
> 
> qui是我的命令出现问题，以下是我使用的命令： `CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 10027 --nproc_per_node=1 tools/relation_test_net_cy.py --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX False MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL False MODEL.ROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE TDE MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE sum MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER motifs TEST.IMS_PER_BATCH 1 DTYPE "float16" GLOVE_DIR /home/njcam/cy/glove MODEL.PRETRAINED_DETECTOR_CKPT /home/njcam/cy/checkpoints/causal-motifs-sgdet OUTPUT_DIR /home/njcam/cy/checkpoints/causal-motifs-sgdet TEST.CUSTUM_EVAL True TEST.CUSTUM_PATH /home/njcam/cy/coco/Scene-Graph-Benchmark.pytorch/datasets/test.jpg DETECTED_SGG_DIR /home/njcam/cy/checkpoints/output_pat`

我发现错误的地方了，是在`TEST.CUSTUM_PATH /home/njcam/cy/coco/Scene-Graph-Benchmark.pytorch/datasets/test.jpg`中，这里应当指向的是包含自定义测试图片的父文件夹，而不是图片本身，应当为`TEST.CUSTUM_PATH /home/njcam/cy/coco/Scene-Graph-Benchmark.pytorch/datasets`

**Comment by zuiyeye** [comment]
> > @yayalvhai
> > Could you tell me how you solved the problem? Did you really have to download the VG dataset in the end
> 
> yeah. If just SGDet, you do not need to download VG datasets

但我只有在配置好VG数据集之后才成功。顺带一提，在解决这个问题后在路径`maskrcnn_benchmark/data/datasets/visual_genome.py`中需要将np.float 替换为 float 或 np.float64，np.bool 替换为 bool 或 np.bool64,因为np.float和 np.bool已被弃用。
