### ISSUE TITLE
Configuration and hyper parameters for achieving reported performance

### ISSUE THREAD

**Issue by lytning98** [KaihuaTang/Scene-Graph-Benchmark.pytorch#21]
Hi Kaihua,

Thanks for your great framework!
I met some trouble in reproducing reported performance on transformer model. For PredCls task, there's a gap of about 0.3 percent between my results (66.97) and reported performance (67.29).

I used provided pretrained detector and `configs/e2e_relation_X_101_32_8_FPN_1x.yaml` as config. As instructed in `METRICS.md` I set `SOLVER.BASE_LR` to `0.001`.
My environment is like:
```
python=3.7.6
pytorch=1.2.0
torchvision=0.4.0
CUDA=10.0
```

I've tried only on transformer model for PredCls task, so I'm not sure whether this issue exists on other tasks/models or not. Are there any additional changes on config or hyper parameters that's needed to achieve the reported performance, or is there something that I missed in the documents?

Thanks for your help!

**Comment by KaihuaTang** [comment]
In my reported results, the default SOLVER.BASE_LR is 0.01. I'm not sure whether this is the problem.

**Comment by lytning98** [comment]
> In my reported results, the default SOLVER.BASE_LR is 0.01. I'm not sure whether this is the problem.

Thanks for your quick reply! I got correct performance for PredCls task using default `SOLVER.BASE_LR`.
