### ISSUE TITLE
broken link for /vg/VG-SGG-with-attri.h5

### ISSUE THREAD

**Issue by Catchip** [KaihuaTang/Scene-Graph-Benchmark.pytorch#215]
It seems that the download link for /vg/VG-SGG-with-attri.h5 is broken.

**Comment by KaihuaTang** [comment]
Please try the following link:

**Comment by KaihuaTang** [comment]
Please try the following link:
https://1drv.ms/f/s!AmRLLNf6bzcir8xdJNPnaIER5u540w?e=yzQE0u

or

https://pan.baidu.com/s/1oyPQBDHXMQ5Tsl0jy5OzgA  Extraction code：1234

**Comment by KaihuaTang** [comment]
Thank you for your support. I've added your github username to the following page (assuming you don't mind): https://kaihuatang.github.io/supporters.html

**Comment by Catchip** [comment]
Thanks
