### ISSUE TITLE
error in inferencing

### ISSUE THREAD

**Issue by wynterr** [KaihuaTang/Scene-Graph-Benchmark.pytorch#27]
Hi, I'm evaluating on VG Dataset using the pretrained model you provided. And I got this warning from time to time. 

> 2020-05-04 20:19:40,514 maskrcnn_benchmark.inference WARNING: WARNING! WARNING! WARNING! WARNING! WARNING! WARNING!Number of images that were gathered from multiple processes is nota contiguous set. Some images might be missing from the evaluation

I found it somehow related to the gpu number I am using. Sometime I got the warning but when I change the gpu number and run it in a completely config, I didn't got it any more. It's strange and I don't know in what condition will I got this warning.
Do you have any idea about what's going on here?
Thanks!

**Comment by KaihuaTang** [comment]
I've never seen this message before. This problem might inherit from maskrcnn_benchmark. FYI, I always train and evaluate the SGG model by 2 GPUs.

**Comment by wynterr** [comment]
> 
> 
> I've never seen this message before. This problem might be inherited from maskrcnn_benchmark. FYI, I always train and evaluate the SGG model by 2 GPUs.

Ok,thanks. I'm getting this warning when using 6 gpus. I'll check with maskrcnn_benchmark codebase.
