### ISSUE TITLE
repository not found

### ISSUE THREAD

**Issue by lymoon3129** [KaihuaTang/Scene-Graph-Benchmark.pytorch#3]
在环境配置的最后一步被绊倒了，尝试git clone https://github.com/KaihuaTang/scene-graph-benchmark的时候提示Repository not found.

大佬托管地址更改了嘛

**Comment by KaihuaTang** [comment]
my mistake, it should be https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch.git

**Comment by KaihuaTang** [comment]
如果之后还有别的问题也欢迎告诉我，防止我写instruction的时候有遗漏
