### ISSUE TITLE
`KeyError: 'labels'` for predictions while doing PredCls

### ISSUE THREAD

**Issue by zyong812** [KaihuaTang/Scene-Graph-Benchmark.pytorch#34]
## ❓ Questions and Help

In `vg_eval.py`, following lines will report error `KeyError: 'labels'` while testing. 
```
if mode == 'predcls':
    label = prediction.get_field('labels').detach().cpu().numpy()
```
Since prediction only have two extra fields: `pred_labels` and `pred_scores`.

Is this a bug? Thanks

**Comment by kesaroid** [comment]
Hey @zyong812 , were you able to fix this?
