### ISSUE TITLE
About the "baseline" in the paper.

### ISSUE THREAD

**Issue by Kenneth-Wong** [KaihuaTang/Scene-Graph-Benchmark.pytorch#39]
## ❓ Questions and Help
I observed that there is a little difference between directly using the MotifPredictor and using CausalPredictor for Motif (other methods also have this problem). So which one do you use to train the "baseline" in the paper for every method (Motif, VCTree, VTransE)?

**Comment by KaihuaTang** [comment]
CausalPredictor is what I used to report 'baseline' in the paper for fair comparison (same model, same fusion function, just without TDE inference), although  MotifPredictor and CausalPredictor with Motif usually have very similar results.

**Comment by Kenneth-Wong** [comment]
Thanks!
