### ISSUE TITLE
About the pair accuracy

### ISSUE THREAD

**Issue by Kenneth-Wong** [KaihuaTang/Scene-Graph-Benchmark.pytorch#40]
## ❓ Questions and Help
I wonder if you can get the  "PREDDET" (no graph constraints) results reported in the paper "Neural Motifs [CVPR 2018]" or the so-called "PREDCLS" in "Graph Contrastive Loss [CVPR 2019]". I know that this is actually the "PairAccuracy" in your codes. The results in those 2 papers are about 96%-98%. However, I only got about 84-85% with your PairAccuracy. I think that your code is right. But your paper did not report this result. So I may need your help. Thanks.

**Comment by Kenneth-Wong** [comment]
The results on other metrics are all normal, but only the results on "PREDDET", i.e., "PairAccuracy", are not as expected.

**Comment by KaihuaTang** [comment]
To be clear, PairAccuracy is the Top@K Accuracy (A@K) in the printed results, which is used by "Graph Contrastive Loss [CVPR 2019]", which uses ground-truth subject-object pair information. The original paper only use A@K for PredCls and SGCls, and they don't use it in PredDet, so my code only print A@K in PredCls and SGCls.  As to the no graph constraints, it printed as ngR@K. It is NOT PairAccuracy in my code.  You can read https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/blob/master/METRICS.md#explanation-of-our-metrics to see their difference.

**Comment by Kenneth-Wong** [comment]
I know that your original code only prints the traditional recall@K under no graph constraints. However, actually we can also get the pair accuracy under no graph constraints, which is reported as "PREDDET" in the motif [CVPR 2018], Table 3 in the supplementary material. If I'm right, the "pair accuracy" is the same as "PREDDET". We only need to re-set the "pred_pair_in_gt" after obtaining all the no graph constraints top predicted pairs. (Ummm I think it's right...)

The results mentioned above are about 96~98% in Motif, as well as those in Contrastive Loss [CVPR 2019]. But mine is only about 85%. So I wonder if there are any other settings. Or just because my implementation is wrong? But my results on other metrics are as expected......

**Comment by KaihuaTang** [comment]
Yes, you are right, A@K + no graph constraint in PredCls should be equivalent to PREDDET.  I think I know the problem of your implementation. If I understand correctly, you first select Top K no graph constraint  candidates, then apply GT pair selection(pred_pair_in_gt), which means after GT pair selection, the remaining pairs **are less than K**. You should first apply GT pair selection then  select top K to calculate Recall.

**Comment by Kenneth-Wong** [comment]
Yes. I indeed first apply GT pair selection then select top K. I think my implementation is right. Here is the code. 

(1) In the SGRecall: calculate_recall function, I add the following codes to obtain all the no graph constraint candidates ("nogc_pred_rels") and the markers to indicate whether they are the gt pair ("local_container['nogc@%d_pred_pair_in_gt' % nogc_num]").  (Here the nogc_num is 50, and if in VRD, it may be 10, 70, etc.): 
```
# compute the no graph constraint setting pred_rels
        obj_scores_per_rel = obj_scores[pred_rel_inds].prod(1)
        nogc_overall_scores = obj_scores_per_rel[:, None] * rel_scores[:, 1:]  # Nr * 50
        sorted_inds = np.argsort(nogc_overall_scores, axis=-1)[:, ::-1]
        sorted_nogc_overall_scores = np.sort(nogc_overall_scores, axis=-1)[:, ::-1]
        gt_pair_idx = gt_rels[:, 0] * 10000 + gt_rels[:, 1]
        for nogc_num in nogc_thres_num:
            nogc_score_inds_ = argsort_desc(sorted_nogc_overall_scores[:, :nogc_num])[:100]
            nogc_pred_rels = np.column_stack((pred_rel_inds[nogc_score_inds_[:, 0]],
                                              sorted_inds[nogc_score_inds_[:, 0], nogc_score_inds_[:, 1]] + 1))
            nogc_pred_scores = rel_scores[nogc_score_inds_[:, 0],
                                          sorted_inds[nogc_score_inds_[:, 0], nogc_score_inds_[:, 1]] + 1]
            pred_triplets, pred_triplet_boxes, pred_triplet_scores = _triplet(
                nogc_pred_rels, pred_classes, pred_boxes, nogc_pred_scores, obj_scores)

            # prepare the gt rel signal to be used in PairAccuracy:
            pred_pair_idx = nogc_pred_rels[:, 0] * 10000 + nogc_pred_rels[:, 1]
            local_container['nogc@%d_pred_pair_in_gt' % nogc_num] = \
                (pred_pair_idx[:, None] == gt_pair_idx[None, :]).sum(-1) > 0

            # Compute recall. It's most efficient to match once and then do recall after
            pred_to_gt = _compute_pred_matches(
                gt_triplets,
                pred_triplets,
                gt_triplet_boxes,
                pred_triplet_boxes,
                iou_thrs,
                phrdet=False,
            )

            local_container['nogc@%d_pred_to_gt' % nogc_num] = pred_to_gt
```

(2) Then, in the SGPairAccuracy- calcuate_recall function, I modify the code as:
```
        if mode != 'sgdet':
            gt_pair_pred_to_gt = []
            for p, flag in zip(prediction_to_gt, pred_pair_in_gt):
                if flag:
                    gt_pair_pred_to_gt.append(p)
            for k in target_hit:
                # to calculate accuracy, only consider those gt pairs
                # This metric is used by "Graphical Contrastive Losses for Scene Graph Parsing"
                if len(gt_pair_pred_to_gt) > 0:
                    gt_pair_match = reduce(np.union1d, gt_pair_pred_to_gt[:k])
                else:
                    gt_pair_match = []
                target_hit[k].append(float(len(gt_pair_match)))
                target_count[k].append(float(gt_rels.shape[0]))
```
You can see that the first loop selects the gt pairs. Then the top K are selected.

**Comment by Kenneth-Wong** [comment]
I wonder if I can add your WeChat for further communication with you. I have sent an email to your Gmail. I am a Chinese Ph.D. student who is also working in this field.

**Comment by KaihuaTang** [comment]
Try removing the [:100] in "nogc_score_inds_ = argsort_desc(sorted_nogc_overall_scores[:, :nogc_num])[:100]"

**Comment by Kenneth-Wong** [comment]
Wow, it works! Thanks!
