### ISSUE TITLE
Problem of loading word vectors

### ISSUE THREAD

**Issue by ZhuYun97** [KaihuaTang/Scene-Graph-Benchmark.pytorch#44]
## ❓ Questions and Help
When I train or test model, this warning will appear. Does this warning make effect on the performance of model? And, how to avoid this warning?
```python
loading word vectors from /home/mist/glove/glove.6B.200d.pt
__background__ -> __background__ 
fail on __background__
loading word vectors from /home/mist/glove/glove.6B.200d.pt
__background__ -> __background__ 
fail on __background__
```

**Comment by KaihuaTang** [comment]
it won't affect the performance. because '__background__' is not a valid word, so the glove word embedding can't give an initialization, which means it will be initialized randomly.

**Comment by ZhuYun97** [comment]
Thanks a lot
