### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by nullkatar** [KaihuaTang/Scene-Graph-Benchmark.pytorch#48]
## ❓ Questions and Help
Hello there! I am running the following command: `
 CUDA_VISIBLE_DEVICES=1 python -m torch.distribode=1 tools/relation_train_net.py --config-file "configs/e2e_relation_X_101_32_8_FPN_1x.yaml" MODEL.ROI_RELATION_HEAD.USE_GT_BOX True MODEL.ROI_RROI_RELATION_HEAD.PREDICTOR CausalAnalysisPredictor MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE none MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE suR motifs  SOLVER.IMS_PER_BATCH 12 TEST.IMS_PER_BATCH 2 DTYPE "float16" SOLVER.MAX_ITER 50000 SOLVER.VAL_PERIOD 2000 SOLVER.CHECKPOINT_PERIOD 2000GB/Scene-Graph-Benchmark.pytorch MODEL.PRETRAINED_DETECTOR_CKPT /home/lkochiev/checkpoints/pretrained_faster_rcnn/model_final.pth OUTPUT_DIR /home/lkochiev/checkpoints/causal-motifs-sgcls-exmp` And I expect the model to start training, while I'm getting the following:

` File "/home/lkochiev/Documents/SFU/NSM/SGB/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/modeling/roi_heads/relation_head/model_motifs.py", line 178, in forward'
  assert l_batch == 1 
AssertionError`

Could I ask for some tips how to solve it? 
I am using PyTorch 1.4, CUDA 10.0, 2080ti. Thank you in advance!

**Comment by KaihuaTang** [comment]
Change TEST.IMS_PER_BATCH to 1 may solve the problem.

**Comment by nullkatar** [comment]
Thank you for such a quick response, it helped!
