### ISSUE TITLE
'get_img_info' Error  on SGDet on Custom Images

### ISSUE THREAD

**Issue by EricWWWW** [KaihuaTang/Scene-Graph-Benchmark.pytorch#53]
## ❓ Questions and Help
I run `SGDet on Custom Images` on my own images, but the code load the 'VG information'(eg, height and width) in `datasets/image_data.json` in `maskrcnn_benchmark/data/datasets/visual_genome.py` line `121` function`get_custom_imgs`. This leads to a mismatch   between my images and the VG images. Should I make a json file which contains `width and height`information on my own image? or what shoule I do?

**Comment by Opdoop** [comment]
@EricWWWW Have you solved this problem?  I may be facing the same issue.

**Comment by EricWWWW** [comment]
> @EricWWWW Have you solved this problem? I may be facing the same issue.

You need to generate a json file in the same format as vg to contain the information of your custom image
