### ISSUE TITLE
About used GPU number for training

### ISSUE THREAD

**Issue by shine-lcy** [KaihuaTang/Scene-Graph-Benchmark.pytorch#6]
Firstly, thanks for this excellent work.
I notice that we need 4 gpus for training detector and 2gpus for training SGG.
eg., for detector,
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --master_port 10001 --nproc_per_node=4 tools/detector_pretrain_net.py ...(omit other parameters)
```
If I wanna train it just using ONE gpu, can I manually reduce SOLVER.IMS_PER_BATCH and run
```
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --master_port 10001 --nproc_per_node=1 tools/detector_pretrain_net.py ...(omit other parameters)
```
I tried it and it can start training. I want to ask if there are any problem with above command? What's the right command for single GPU training?

**Comment by KaihuaTang** [comment]
First, your command is correct. But for the single GPU, there is no need to use distributed training. You can follow the single GPU training instruction from https://github.com/facebookresearch/maskrcnn-benchmark , i.e., directly start with "python tools/XXX.py ........"

**Comment by KaihuaTang** [comment]
As to the batch size, it depends on the memory of your GPU. You can start with the reduced SOLVER.IMS_PER_BATCH, then check whether you can squeeze in 1 or 2 images or not? After all, the larger the batch size is, the better the performance will be (normally).

**Comment by shine-lcy** [comment]
Can't believe got such a detailed and prompt response. Thank you!
