### ISSUE TITLE
Probable bug in image retrieval code

### ISSUE THREAD

**Issue by mods333** [KaihuaTang/Scene-Graph-Benchmark.pytorch#64]
Hi, I was trying to use the code for the image retrieval task. The code in 'dataloader.py` and 'preprocessing.py` seem to be somewhat inconsistent. 
In `dataloader.py` there is `_generate_tensor_by_idx` that looks for `'image_graph` and `'text_graph` key in the `img_txt_sg` variable
![image](https://user-images.githubusercontent.com/8975010/88887247-df7ba500-d1f0-11ea-942a-8118ae5a17b3.png)

However in the preprocessing code the output dictionary created had only two keys `img` and `txt`
![image](https://user-images.githubusercontent.com/8975010/88887391-2a95b800-d1f1-11ea-9637-badd43dc8af7.png)

I was wondering if there is something missing in the code or if I am doing something wrong.

**Comment by KaihuaTang** [comment]
sorry, my fault. I think 'image_graph' and 'test_graph' keys have been discarded, which means the following 4 lines can be removed from dataloader.py

![image](https://user-images.githubusercontent.com/24402685/88889018-fb735b00-d271-11ea-9701-dd43913b3e39.png)

**Comment by mods333** [comment]
I think those lines are required as in the scene graph encoding model (`modelv2.py`), the graph is used as attention weights.
![image](https://user-images.githubusercontent.com/8975010/88960618-a6771b00-d258-11ea-96b4-417415ab3762.png)

From the code and the paper, what I understand is that the `image graph` corresponds to the following equation in the paper.
![image](https://user-images.githubusercontent.com/8975010/88960829-f2c25b00-d258-11ea-84f9-60d0aba82d0b.png)

But I am not sure how the `text_graph` is to be generated

**Comment by KaihuaTang** [comment]
text_graph should be implemented the same as image_gaph.  I didn't differentiate them in structure except for the vocabulary.  sorry that I lost this part of codes.  preprocessing.py was merged from several independent jupyter notes. I think I forgot to paste some functions.

**Comment by mods333** [comment]
I will try to figure out the missing part. Thanks for the help. Also thanks a lot for sharing this repository. Amazing work!

**Comment by cws7777** [comment]
@mods333 Have you figured out the missing part? because I'm kinda lost.. Thanks! :)
