### ISSUE TITLE
Problem when run on custom images

### ISSUE THREAD

**Issue by liuhl-source** [KaihuaTang/Scene-Graph-Benchmark.pytorch#69]
I have tried to fix the bug reported in #67 , but a new bug incurred.

Traceback (most recent call last):
  File "tools/relation_test_net.py", line 113, in <module>
    main()
  File "tools/relation_test_net.py", line 95, in main
    data_loaders_val = make_data_loader(cfg, mode="test", is_distributed=distributed)
  File ".../Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/build.py", line 224, in make_data_loader
    batch_sampler = make_batch_data_sampler(
  File "/..../Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/build.py", line 140, in make_batch_data_sampler
    aspect_ratios = _compute_aspect_ratios(dataset)
  File "/..../Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/build.py", line 128, in _compute_aspect_ratios
    img_info = dataset.get_img_info(i)
  File "/...../Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/data/datasets/visual_genome.py", line 143, in get_img_info
    return self.img_info[index]
AttributeError: 'VGDataset' object has no attribute 'img_info'

**Comment by KaihuaTang** [comment]
Try using the following function to replace original get_custom_imgs in visual_genome.py
If it works please tell me, so I can fix this bug in master branch.
![image](https://user-images.githubusercontent.com/24402685/90211297-e0cce480-de22-11ea-9c1a-840c6c6d5393.png)

**Comment by liuhl-source** [comment]
work~ thank you

**Comment by Kritz23** [comment]
Hi @liuhl-source , did you get the "custom_prediction.json" file as output? I am also trying to run on custom images. I did all the recent and necessary changes but I'm stuck on this error.
 
FileNotFoundError: [Errno 2] No such file or directory: 'causal_motifs_sgdet/VG_stanford_filtered_with_attribute_train_statistics.cache'

I have downloaded the pre-trained model folder ("upload_causal_motif_sgdet") and renamed it to the above one. In that folder,("VG_stanford_filtered_with_attribute_train_statistics.cache") file is already present.
The last_checkpoint file on my machine is ("MODEL.PRETRAINED_DETECTOR_CKPT causal_motifs_sgdet/model_0028000.pth").
Can you please help if you know what is wrong?

**Comment by Ankit-Vohra** [comment]
Hi @liuhl-source , after solving your error, this error pops up. 
AttributeError: 'VGDataset' object has no attribute 'gt_classes'
Did you solve this? Also, my question is why does it require ground truth for SGDET on custom images?
