### ISSUE TITLE
subprocess.CalledProcessError : returned non-zero exit status 255.

### ISSUE THREAD

**Issue by shipra25jain** [KaihuaTang/Scene-Graph-Benchmark.pytorch#77]
## ❓ Questions and Help
Hi Kaihua,
Thank you for the great repository. However, I am getting following error in SGDet for custom images. I have followed all the instructions in install readme and have compatible version of cuda and pytorch :

subprocess.CalledProcessError: Command '['/Midgard/home/shipra/miniconda3/envs/scene_graph_benchmark/bin/python', '-u', 'tools/relation_test_net.py', '--local_rank=0', '--config-file', 'configs/e2e_relation_X_101_32_8_FPN_1x.yaml', 'MODEL.ROI_RELATION_HEAD.USE_GT_BOX', 'False', 'MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL', 'False', 'MODEL.ROI_RELATION_HEAD.PREDICTOR', 'CausalAnalysisPredictor', 'MODEL.ROI_RELATION_HEAD.CAUSAL.EFFECT_TYPE', 'none', 'MODEL.ROI_RELATION_HEAD.CAUSAL.FUSION_TYPE', 'sum', 'MODEL.ROI_RELATION_HEAD.CAUSAL.CONTEXT_LAYER', 'motifs', 'TEST.IMS_PER_BATCH', '1', 'DTYPE', 'float16', 'GLOVE_DIR', '/Midgard/home/shipra/workspace/Scene-Graph-Benchmark.pytorch/glove', 'MODEL.PRETRAINED_DETECTOR_CKPT', '/Midgard/home/shipra/workspace/Scene-Graph-Benchmark.pytorch/pretrained_model/casual_motif_sgdet', 'OUTPUT_DIR', '/Midgard/home/shipra/workspace/Scene-Graph-Benchmark.pytorch/pretrained_model/casual_motif_sgdet', 'TEST.CUSTUM_EVAL', 'True', 'TEST.CUSTUM_PATH', '/Midgard/home/shipra/human_friendly_reg/pyutils/refer2/data/images/val2014', 'DETECTED_SGG_DIR', '/Midgard/home/shipra/workspace/Scene-Graph-Benchmark.pytorch/output', 'MODEL.WEIGHT', '/Midgard/home/shipra/workspace/Scene-Graph-Benchmark.pytorch/pretrained_model/casual_motif_sgdet/model_0028000.pth']' returned non-zero exit status 255.

**Comment by BooPatienze** [comment]
Hi, @shipra25jain I meet the same issue, could you tell me what's your solution? Thanks very much.
