### ISSUE TITLE
Size mismatch when loading state dict of pretrained Faster R-CNN model

### ISSUE THREAD

**Issue by BooPatienze** [KaihuaTang/Scene-Graph-Benchmark.pytorch#78]
## ❓ Questions and Help
I tried to train PredCls task using the pretrained Faster R-CNN model (download from Baiduyun). So I run the command on Ubuntu 18.04:
```
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch 
  --master_port 10004 
  --nproc_per_node=4 tools/relation_train_net.py 
  --config-file "configs/e2e_relation_R_101_FPN_1x.yaml" 
  SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 4 DTYPE "float16" 
  SOLVER.MAX_ITER 25000 SOLVER.STEPS "(8000, 16000)" 
  GLOVE_DIR /home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/checkpoints/glove 
  MODEL.PRETRAINED_DETECTOR_CKPT /home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/checkpoints/pretrained_faster_rcnn/model_final.pth 
  OUTPUT_DIR /home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/checkpoints/relation_motif 
  SOLVER.PRE_VAL False 
  MODEL.ROI_RELATION_HEAD.USE_GT_BOX True 
  MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True
```
I got these error messages:
```
Traceback (most recent call last):
  File "tools/relation_train_net.py", line 379, in <module>
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.bn3.running_var                                                                                    loaded from module.backbone.body.layer3.8.bn3.running_var           of shape (1024,)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.bn3.weight                                                                                         loaded from module.backbone.body.layer3.8.bn3.weight                of shape (1024,)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.conv1.weight                                                                                       loaded from module.backbone.body.layer3.8.conv1.weight              of shape (1024, 1024, 1, 1)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.conv2.weight                                                                                       loaded from module.backbone.body.layer3.8.conv2.weight              of shape (1024, 32, 3, 3)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.conv3.weight                                                                                       loaded from module.backbone.body.layer3.8.conv3.weight              of shape (1024, 1024, 1, 1)
    main()
  File "tools/relation_train_net.py", line 372, in main
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.bias                                                                                           loaded from module.backbone.body.layer3.9.bn1.bias                  of shape (1024,)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.running_mean                                                                                   loaded from module.backbone.body.layer3.9.bn1.running_mean          of shape (1024,)
    model = train(cfg, args.local_rank, args.distributed, logger)
  File "tools/relation_train_net.py", line 106, in train
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.running_var                                                                                    loaded from module.backbone.body.layer3.9.bn1.running_var           of shape (1024,)
    checkpointer.load(cfg.MODEL.PRETRAINED_DETECTOR_CKPT, with_optim=False, load_mapping=load_mapping)
  File "/home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/checkpoint.py", line 64, in load
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.weight                                                                                         loaded from module.backbone.body.layer3.9.bn1.weight                of shape (1024,)
    self._load_model(checkpoint, load_mapping)
  File "/home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/checkpoint.py", line 104, in _load_model
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.bias                                                                                           loaded from module.backbone.body.layer3.9.bn2.bias                  of shape (1024,)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.running_mean                                                                                   loaded from module.backbone.body.layer3.9.bn2.running_mean          of shape (1024,)
    load_state_dict(self.model, checkpoint.pop("model"), load_mapping)
  File "/home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/model_serialization.py", line 94, in load_state_dict
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.running_var                                                                                    loaded from module.backbone.body.layer3.9.bn2.running_var           of shape (1024,)
    model.load_state_dict(model_state_dict)
  File "/home/lpz/workspace/SceneGraphParse/sgg_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.weight                                                                                         loaded from module.backbone.body.layer3.9.bn2.weight                of shape (1024,)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.bias                                                                                           loaded from module.backbone.body.layer3.9.bn3.bias                  of shape (1024,)
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.running_mean                                                                                   loaded from module.backbone.body.layer3.9.bn3.running_mean          of shape (1024,)
    self.__class__.__name__, "\n\t".join(error_msgs)))
2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.running_var                                                                                    loaded from module.backbone.body.layer3.9.bn3.running_var           of shape (1024,)
2020-08-19 08:31:36,540 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.weight                                                                                         loaded from module.backbone.body.layer3.9.bn3.weight                of shape (1024,)
RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
        size mismatch for module.backbone.body.layer1.0.conv1.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
        size mismatch for module.backbone.body.layer1.0.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.conv2.weight: copying a param with shape torch.Size([256, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for module.backbone.body.layer1.0.bn2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.bn2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.bn2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.bn2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.0.conv3.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 64, 1, 1]).
        size mismatch for module.backbone.body.layer1.1.conv1.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 256, 1, 1]).
        size mismatch for module.backbone.body.layer1.1.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.conv2.weight: copying a param with shape torch.Size([256, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
        size mismatch for module.backbone.body.layer1.1.bn2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.bn2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.bn2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.bn2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.1.conv3.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 64, 1, 1]).
        size mismatch for module.backbone.body.layer1.2.conv1.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 256, 1, 1]).
        size mismatch for module.backbone.body.layer1.2.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.2.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.2.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
        size mismatch for module.backbone.body.layer1.2.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
......blabla size mismatch info......
```
It seems telling me the current model size need to be modified to the pretrained model size, otherwise could not load param, right? If so, where should I modify? Thank you for your help~

**Comment by BooPatienze** [comment]
I just comment this code:
`align_and_update_state_dicts(model_state_dict, loaded_state_dict, load_mapping)`
in maskrcn_benchmark/utils/model_serialization.py, load_state_dict()
then no errors

**Comment by supremelcs** [comment]
> ## ❓ Questions and Help
> I tried to train PredCls task using the pretrained Faster R-CNN model (download from Baiduyun). So I run the command on Ubuntu 18.04:
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch 
>   --master_port 10004 
>   --nproc_per_node=4 tools/relation_train_net.py 
>   --config-file "configs/e2e_relation_R_101_FPN_1x.yaml" 
>   SOLVER.IMS_PER_BATCH 8 TEST.IMS_PER_BATCH 4 DTYPE "float16" 
>   SOLVER.MAX_ITER 25000 SOLVER.STEPS "(8000, 16000)" 
>   GLOVE_DIR /home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/checkpoints/glove 
>   MODEL.PRETRAINED_DETECTOR_CKPT /home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/checkpoints/pretrained_faster_rcnn/model_final.pth 
>   OUTPUT_DIR /home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/checkpoints/relation_motif 
>   SOLVER.PRE_VAL False 
>   MODEL.ROI_RELATION_HEAD.USE_GT_BOX True 
>   MODEL.ROI_RELATION_HEAD.USE_GT_OBJECT_LABEL True
> ```
> 
> I got these error messages:
> 
> ```
> Traceback (most recent call last):
>   File "tools/relation_train_net.py", line 379, in <module>
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.bn3.running_var                                                                                    loaded from module.backbone.body.layer3.8.bn3.running_var           of shape (1024,)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.bn3.weight                                                                                         loaded from module.backbone.body.layer3.8.bn3.weight                of shape (1024,)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.conv1.weight                                                                                       loaded from module.backbone.body.layer3.8.conv1.weight              of shape (1024, 1024, 1, 1)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.conv2.weight                                                                                       loaded from module.backbone.body.layer3.8.conv2.weight              of shape (1024, 32, 3, 3)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.8.conv3.weight                                                                                       loaded from module.backbone.body.layer3.8.conv3.weight              of shape (1024, 1024, 1, 1)
>     main()
>   File "tools/relation_train_net.py", line 372, in main
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.bias                                                                                           loaded from module.backbone.body.layer3.9.bn1.bias                  of shape (1024,)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.running_mean                                                                                   loaded from module.backbone.body.layer3.9.bn1.running_mean          of shape (1024,)
>     model = train(cfg, args.local_rank, args.distributed, logger)
>   File "tools/relation_train_net.py", line 106, in train
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.running_var                                                                                    loaded from module.backbone.body.layer3.9.bn1.running_var           of shape (1024,)
>     checkpointer.load(cfg.MODEL.PRETRAINED_DETECTOR_CKPT, with_optim=False, load_mapping=load_mapping)
>   File "/home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/checkpoint.py", line 64, in load
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn1.weight                                                                                         loaded from module.backbone.body.layer3.9.bn1.weight                of shape (1024,)
>     self._load_model(checkpoint, load_mapping)
>   File "/home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/checkpoint.py", line 104, in _load_model
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.bias                                                                                           loaded from module.backbone.body.layer3.9.bn2.bias                  of shape (1024,)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.running_mean                                                                                   loaded from module.backbone.body.layer3.9.bn2.running_mean          of shape (1024,)
>     load_state_dict(self.model, checkpoint.pop("model"), load_mapping)
>   File "/home/lpz/workspace/SceneGraphParse/Scene-Graph-Benchmark.pytorch/maskrcnn_benchmark/utils/model_serialization.py", line 94, in load_state_dict
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.running_var                                                                                    loaded from module.backbone.body.layer3.9.bn2.running_var           of shape (1024,)
>     model.load_state_dict(model_state_dict)
>   File "/home/lpz/workspace/SceneGraphParse/sgg_benchmark/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn2.weight                                                                                         loaded from module.backbone.body.layer3.9.bn2.weight                of shape (1024,)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.bias                                                                                           loaded from module.backbone.body.layer3.9.bn3.bias                  of shape (1024,)
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.running_mean                                                                                   loaded from module.backbone.body.layer3.9.bn3.running_mean          of shape (1024,)
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> 2020-08-19 08:31:36,539 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.running_var                                                                                    loaded from module.backbone.body.layer3.9.bn3.running_var           of shape (1024,)
> 2020-08-19 08:31:36,540 maskrcnn_benchmark.utils.model_serialization INFO: REMATCHING! module.backbone.body.layer3.9.bn3.weight                                                                                         loaded from module.backbone.body.layer3.9.bn3.weight                of shape (1024,)
> RuntimeError: Error(s) in loading state_dict for DistributedDataParallel:
>         size mismatch for module.backbone.body.layer1.0.conv1.weight: copying a param with shape torch.Size([256, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 64, 1, 1]).
>         size mismatch for module.backbone.body.layer1.0.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.conv2.weight: copying a param with shape torch.Size([256, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
>         size mismatch for module.backbone.body.layer1.0.bn2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.bn2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.bn2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.bn2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.0.conv3.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 64, 1, 1]).
>         size mismatch for module.backbone.body.layer1.1.conv1.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 256, 1, 1]).
>         size mismatch for module.backbone.body.layer1.1.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.conv2.weight: copying a param with shape torch.Size([256, 8, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3]).
>         size mismatch for module.backbone.body.layer1.1.bn2.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.bn2.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.bn2.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.bn2.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.1.conv3.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 64, 1, 1]).
>         size mismatch for module.backbone.body.layer1.2.conv1.weight: copying a param with shape torch.Size([256, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 256, 1, 1]).
>         size mismatch for module.backbone.body.layer1.2.bn1.weight: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.2.bn1.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.2.bn1.running_mean: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
>         size mismatch for module.backbone.body.layer1.2.bn1.running_var: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([64]).
> ......blabla size mismatch info......
> ```
> 
> It seems telling me the current model size need to be modified to the pretrained model size, otherwise could not load param, right? If so, where should I modify? Thank you for your help~

Hi, can you successfully run the SGNet on your custom image ? When I run the SGNet on my custom image, I met the same problem as that mentioneed in the following url:

https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch/issues/116#issue-836367563 

I got poor detected results. In other words, the detected bounding box are small and all wrong not matching the objects in my images. In addition, all the detected score are small and less than 0.02. Can you give me some suggestions ? I am a newhand for SGG. Thanks a lots !
