### ISSUE TITLE
How to get attribute information?

### ISSUE THREAD

**Issue by Einstone-rose** [KaihuaTang/Scene-Graph-Benchmark.pytorch#83]
## ❓ Questions and Help
Hi, I ran the evaluation command for custom SGDet with attribute_on as True in "e2e_relation_X_101_32_8_FPN_1x.yaml" (I have trained the detection model with attribute-head on, and train the SGDet model with attribute-head on too). However, the custom_predictions.json file generated does not give attributes in output. I get this info for every image : dict_keys(['bbox', 'bbox_labels', 'bbox_scores', 'rel_pairs', 'rel_labels', 'rel_scores', 'rel_all_scores']). How can I get the attribute information?

**Comment by hflsdupont** [comment]
Hi, I saw you closed the issue. Have you found out the reason?

**Comment by Einstone-rose** [comment]
> Hi, I saw you closed the issue. Have you found out the reason?

Please refer to this. #57
