### ISSUE TITLE
Did you include the code for the self-critics RL training for VCTree?

### ISSUE THREAD

**Issue by alibabadoufu** [KaihuaTang/Scene-Graph-Benchmark.pytorch#88]
## ❓ Questions and Help
Hi, I am trying to find the code where you train the VCTree with self-critics RL algo, but I could not find it. Could you please kindly advise this?

**Comment by KaihuaTang** [comment]
I remove the self-critics RL finetuning in this project for simplicity, because I only need to use the VCTree structure as a baseline to test our TDE method.
