### ISSUE TITLE
Detect Scene Graphs on Your Custom Images

### ISSUE THREAD

**Issue by PipiZong** [KaihuaTang/Scene-Graph-Benchmark.pytorch#91]
## ❓ Questions and Help
Hi,

I tried your command provided in the section, Detect Scene Graphs on Your Custom Images, to see what the scene graph looks like generated from 10 images sampled randomly from VG_100K ( i.e., 1.jpg-10.jpg from the dataset are taken as the custom images). After I visualized one of the scene graphs, I found the bounding box and its label, or the relationships were all predicted wrong. I am wondering if the way I did is wrong or scene graph detection is indeed inaccurate. Could you please give me some suggestions about generating a scene graph given an image without any annotations precisely?

Thanks!

**Comment by kyteinsky** [comment]
Hey @PipiZong,
Can you share the modified code, something is not right when I changed the model weight path using `MODEL.WEIGHT`. It takes the `/home/kaihua...` path and nowhere can I see that nor it is overidden by command line argument.

I would be very grateful if you could share it by any medium suitable :smile: 

Thank you.

**Comment by rayush7** [comment]
@PipiZong I am facing the same problem. Did you manage to resolve the issue?

**Comment by iz2late** [comment]
> Hey @PipiZong,
> Can you share the modified code, something is not right when I changed the model weight path using `MODEL.WEIGHT`. It takes the `/home/kaihua...` path and nowhere can I see that nor it is overidden by command line argument.
> 
> I would be very grateful if you could share it by any medium suitable 😄
> 
> Thank you.

I have the same problem :(
