### ISSUE TITLE
Report 'Num of GT boxes is not matching with num of pred boxes in SGCLS' while evaluating the SGCLS.

### ISSUE THREAD

**Issue by xcppy** [KaihuaTang/Scene-Graph-Benchmark.pytorch#97]
## ❓ Questions and Help
Hi, Kaihua @KaihuaTang, thanks for your great work.  When I evaluate the result of SGCLS on Motif model, the log print `Num of GT boxes is not matching with num of pred boxes in SGCLS.` Why did it happen since the predicted boxes are generated from GT boxes? `MODEL.ROI_RELATION_HEAD.USE_GT_BOX` is set as `**True**.` Is there anything wrong with my settings?

**Comment by ichbill** [comment]
Hi, I countered with the same problem. Did you solve it?

**Comment by yangzhaopeng3** [comment]
Same problem, and the evaluation results are all 0, how did you solve this?
